# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/shacoli/open-project/desktop-uestc/gui/DayTable.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DayTable(object):
    def setupUi(self, DayTable):
        DayTable.setObjectName("DayTable")
        DayTable.resize(362, 911)
        self.centralwidget = QtWidgets.QWidget(DayTable)
        self.centralwidget.setMaximumSize(QtCore.QSize(362, 861))
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 341, 851))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.switch_button = QtWidgets.QPushButton(self.layoutWidget)
        self.switch_button.setObjectName("switch_button")
        self.horizontalLayout.addWidget(self.switch_button)
        self.dateEdit = QtWidgets.QDateEdit(self.layoutWidget)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout.addWidget(self.dateEdit)
        self.date_choose_button = QtWidgets.QPushButton(self.layoutWidget)
        self.date_choose_button.setObjectName("date_choose_button")
        self.horizontalLayout.addWidget(self.date_choose_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.scrollArea = QtWidgets.QScrollArea(self.layoutWidget)
        self.scrollArea.setMinimumSize(QtCore.QSize(196, 600))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -337, 321, 1600))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 1600))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.layoutWidget1 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 301, 74))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label11 = QtWidgets.QLabel(self.layoutWidget1)
        self.label11.setAlignment(QtCore.Qt.AlignCenter)
        self.label11.setObjectName("label11")
        self.verticalLayout_4.addWidget(self.label11)
        self.label12 = QtWidgets.QLabel(self.layoutWidget1)
        self.label12.setAlignment(QtCore.Qt.AlignCenter)
        self.label12.setObjectName("label12")
        self.verticalLayout_4.addWidget(self.label12)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.textBrowser = QtWidgets.QTextBrowser(self.layoutWidget1)
        self.textBrowser.setMaximumSize(QtCore.QSize(174, 70))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_5.addWidget(self.textBrowser)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_6.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_4.addWidget(self.pushButton_6)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_4)
        self.layoutWidget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 100, 301, 74))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label21 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label21.setAlignment(QtCore.Qt.AlignCenter)
        self.label21.setObjectName("label21")
        self.verticalLayout_6.addWidget(self.label21)
        self.label22 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label22.setAlignment(QtCore.Qt.AlignCenter)
        self.label22.setObjectName("label22")
        self.verticalLayout_6.addWidget(self.label22)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.layoutWidget_2)
        self.textBrowser_2.setMaximumSize(QtCore.QSize(174, 70))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalLayout_7.addWidget(self.textBrowser_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_7.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_6.addWidget(self.pushButton_7)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.layoutWidget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 190, 301, 74))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label31 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label31.setAlignment(QtCore.Qt.AlignCenter)
        self.label31.setObjectName("label31")
        self.verticalLayout_8.addWidget(self.label31)
        self.label32 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label32.setAlignment(QtCore.Qt.AlignCenter)
        self.label32.setObjectName("label32")
        self.verticalLayout_8.addWidget(self.label32)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.layoutWidget_3)
        self.textBrowser_3.setMaximumSize(QtCore.QSize(174, 70))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.verticalLayout_9.addWidget(self.textBrowser_3)
        self.horizontalLayout_7.addLayout(self.verticalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_8.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_8.addWidget(self.pushButton_8)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_8)
        self.layoutWidget_4 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 280, 301, 74))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label41 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label41.setAlignment(QtCore.Qt.AlignCenter)
        self.label41.setObjectName("label41")
        self.verticalLayout_10.addWidget(self.label41)
        self.label42 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label42.setAlignment(QtCore.Qt.AlignCenter)
        self.label42.setObjectName("label42")
        self.verticalLayout_10.addWidget(self.label42)
        self.horizontalLayout_9.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.layoutWidget_4)
        self.textBrowser_4.setMaximumSize(QtCore.QSize(174, 70))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.verticalLayout_11.addWidget(self.textBrowser_4)
        self.horizontalLayout_9.addLayout(self.verticalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.pushButton_9.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_10.addWidget(self.pushButton_9)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_10)
        self.layoutWidget_5 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 370, 301, 74))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label51 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label51.setAlignment(QtCore.Qt.AlignCenter)
        self.label51.setObjectName("label51")
        self.verticalLayout_12.addWidget(self.label51)
        self.label52 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label52.setAlignment(QtCore.Qt.AlignCenter)
        self.label52.setObjectName("label52")
        self.verticalLayout_12.addWidget(self.label52)
        self.horizontalLayout_11.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.layoutWidget_5)
        self.textBrowser_5.setMaximumSize(QtCore.QSize(174, 70))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.verticalLayout_13.addWidget(self.textBrowser_5)
        self.horizontalLayout_11.addLayout(self.verticalLayout_13)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_10 = QtWidgets.QPushButton(self.layoutWidget_5)
        self.pushButton_10.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_12.addWidget(self.pushButton_10)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_12)
        self.layoutWidget_6 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 460, 301, 74))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label61 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label61.setAlignment(QtCore.Qt.AlignCenter)
        self.label61.setObjectName("label61")
        self.verticalLayout_14.addWidget(self.label61)
        self.label62 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label62.setAlignment(QtCore.Qt.AlignCenter)
        self.label62.setObjectName("label62")
        self.verticalLayout_14.addWidget(self.label62)
        self.horizontalLayout_13.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.layoutWidget_6)
        self.textBrowser_6.setMaximumSize(QtCore.QSize(174, 70))
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.verticalLayout_15.addWidget(self.textBrowser_6)
        self.horizontalLayout_13.addLayout(self.verticalLayout_15)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pushButton_11 = QtWidgets.QPushButton(self.layoutWidget_6)
        self.pushButton_11.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_14.addWidget(self.pushButton_11)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_14)
        self.layoutWidget_7 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_7.setGeometry(QtCore.QRect(10, 550, 301, 74))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label71 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label71.setAlignment(QtCore.Qt.AlignCenter)
        self.label71.setObjectName("label71")
        self.verticalLayout_16.addWidget(self.label71)
        self.label72 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label72.setAlignment(QtCore.Qt.AlignCenter)
        self.label72.setObjectName("label72")
        self.verticalLayout_16.addWidget(self.label72)
        self.horizontalLayout_15.addLayout(self.verticalLayout_16)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.layoutWidget_7)
        self.textBrowser_7.setMaximumSize(QtCore.QSize(174, 70))
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.verticalLayout_17.addWidget(self.textBrowser_7)
        self.horizontalLayout_15.addLayout(self.verticalLayout_17)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.pushButton_12 = QtWidgets.QPushButton(self.layoutWidget_7)
        self.pushButton_12.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_16.addWidget(self.pushButton_12)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_16)
        self.layoutWidget_8 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_8.setGeometry(QtCore.QRect(10, 640, 301, 74))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label81 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label81.setAlignment(QtCore.Qt.AlignCenter)
        self.label81.setObjectName("label81")
        self.verticalLayout_18.addWidget(self.label81)
        self.label82 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label82.setAlignment(QtCore.Qt.AlignCenter)
        self.label82.setObjectName("label82")
        self.verticalLayout_18.addWidget(self.label82)
        self.horizontalLayout_17.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.layoutWidget_8)
        self.textBrowser_8.setMaximumSize(QtCore.QSize(174, 70))
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.verticalLayout_19.addWidget(self.textBrowser_8)
        self.horizontalLayout_17.addLayout(self.verticalLayout_19)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.pushButton_13 = QtWidgets.QPushButton(self.layoutWidget_8)
        self.pushButton_13.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_18.addWidget(self.pushButton_13)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_18)
        self.layoutWidget_9 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_9.setGeometry(QtCore.QRect(10, 730, 301, 74))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label91 = QtWidgets.QLabel(self.layoutWidget_9)
        self.label91.setAlignment(QtCore.Qt.AlignCenter)
        self.label91.setObjectName("label91")
        self.verticalLayout_20.addWidget(self.label91)
        self.label92 = QtWidgets.QLabel(self.layoutWidget_9)
        self.label92.setAlignment(QtCore.Qt.AlignCenter)
        self.label92.setObjectName("label92")
        self.verticalLayout_20.addWidget(self.label92)
        self.horizontalLayout_19.addLayout(self.verticalLayout_20)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.textBrowser_9 = QtWidgets.QTextBrowser(self.layoutWidget_9)
        self.textBrowser_9.setMaximumSize(QtCore.QSize(174, 70))
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.verticalLayout_21.addWidget(self.textBrowser_9)
        self.horizontalLayout_19.addLayout(self.verticalLayout_21)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.pushButton_14 = QtWidgets.QPushButton(self.layoutWidget_9)
        self.pushButton_14.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_20.addWidget(self.pushButton_14)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_20)
        self.layoutWidget_10 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_10.setGeometry(QtCore.QRect(10, 820, 301, 74))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.layoutWidget_10)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label101 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label101.setAlignment(QtCore.Qt.AlignCenter)
        self.label101.setObjectName("label101")
        self.verticalLayout_22.addWidget(self.label101)
        self.label102 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label102.setAlignment(QtCore.Qt.AlignCenter)
        self.label102.setObjectName("label102")
        self.verticalLayout_22.addWidget(self.label102)
        self.horizontalLayout_21.addLayout(self.verticalLayout_22)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.textBrowser_10 = QtWidgets.QTextBrowser(self.layoutWidget_10)
        self.textBrowser_10.setMaximumSize(QtCore.QSize(174, 70))
        self.textBrowser_10.setObjectName("textBrowser_10")
        self.verticalLayout_23.addWidget(self.textBrowser_10)
        self.horizontalLayout_21.addLayout(self.verticalLayout_23)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.pushButton_15 = QtWidgets.QPushButton(self.layoutWidget_10)
        self.pushButton_15.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_22.addWidget(self.pushButton_15)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_22)
        self.layoutWidget_11 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_11.setGeometry(QtCore.QRect(10, 910, 301, 74))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.layoutWidget_11)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label111 = QtWidgets.QLabel(self.layoutWidget_11)
        self.label111.setAlignment(QtCore.Qt.AlignCenter)
        self.label111.setObjectName("label111")
        self.verticalLayout_24.addWidget(self.label111)
        self.label112 = QtWidgets.QLabel(self.layoutWidget_11)
        self.label112.setAlignment(QtCore.Qt.AlignCenter)
        self.label112.setObjectName("label112")
        self.verticalLayout_24.addWidget(self.label112)
        self.horizontalLayout_23.addLayout(self.verticalLayout_24)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.textBrowser_11 = QtWidgets.QTextBrowser(self.layoutWidget_11)
        self.textBrowser_11.setMaximumSize(QtCore.QSize(174, 70))
        self.textBrowser_11.setObjectName("textBrowser_11")
        self.verticalLayout_25.addWidget(self.textBrowser_11)
        self.horizontalLayout_23.addLayout(self.verticalLayout_25)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.pushButton_16 = QtWidgets.QPushButton(self.layoutWidget_11)
        self.pushButton_16.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_24.addWidget(self.pushButton_16)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_24)
        self.layoutWidget_12 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_12.setGeometry(QtCore.QRect(10, 1000, 301, 74))
        self.layoutWidget_12.setObjectName("layoutWidget_12")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.layoutWidget_12)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label121 = QtWidgets.QLabel(self.layoutWidget_12)
        self.label121.setAlignment(QtCore.Qt.AlignCenter)
        self.label121.setObjectName("label121")
        self.verticalLayout_26.addWidget(self.label121)
        self.label122 = QtWidgets.QLabel(self.layoutWidget_12)
        self.label122.setAlignment(QtCore.Qt.AlignCenter)
        self.label122.setObjectName("label122")
        self.verticalLayout_26.addWidget(self.label122)
        self.horizontalLayout_25.addLayout(self.verticalLayout_26)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.textBrowser_12 = QtWidgets.QTextBrowser(self.layoutWidget_12)
        self.textBrowser_12.setMaximumSize(QtCore.QSize(174, 70))
        self.textBrowser_12.setObjectName("textBrowser_12")
        self.verticalLayout_27.addWidget(self.textBrowser_12)
        self.horizontalLayout_25.addLayout(self.verticalLayout_27)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.pushButton_17 = QtWidgets.QPushButton(self.layoutWidget_12)
        self.pushButton_17.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_26.addWidget(self.pushButton_17)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_26)
        self.add_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.add_button.setGeometry(QtCore.QRect(110, 1544, 111, 41))
        self.add_button.setObjectName("add_button")
        self.layoutWidget_13 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_13.setGeometry(QtCore.QRect(10, 1090, 301, 74))
        self.layoutWidget_13.setObjectName("layoutWidget_13")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.layoutWidget_13)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label131 = QtWidgets.QLabel(self.layoutWidget_13)
        self.label131.setAlignment(QtCore.Qt.AlignCenter)
        self.label131.setObjectName("label131")
        self.verticalLayout_28.addWidget(self.label131)
        self.label132 = QtWidgets.QLabel(self.layoutWidget_13)
        self.label132.setAlignment(QtCore.Qt.AlignCenter)
        self.label132.setObjectName("label132")
        self.verticalLayout_28.addWidget(self.label132)
        self.horizontalLayout_27.addLayout(self.verticalLayout_28)
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.textBrowser_13 = QtWidgets.QTextBrowser(self.layoutWidget_13)
        self.textBrowser_13.setMaximumSize(QtCore.QSize(174, 70))
        self.textBrowser_13.setObjectName("textBrowser_13")
        self.verticalLayout_29.addWidget(self.textBrowser_13)
        self.horizontalLayout_27.addLayout(self.verticalLayout_29)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.pushButton_18 = QtWidgets.QPushButton(self.layoutWidget_13)
        self.pushButton_18.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_28.addWidget(self.pushButton_18)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_28)
        self.layoutWidget_14 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_14.setGeometry(QtCore.QRect(10, 1180, 301, 74))
        self.layoutWidget_14.setObjectName("layoutWidget_14")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.layoutWidget_14)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.label141 = QtWidgets.QLabel(self.layoutWidget_14)
        self.label141.setAlignment(QtCore.Qt.AlignCenter)
        self.label141.setObjectName("label141")
        self.verticalLayout_30.addWidget(self.label141)
        self.label142 = QtWidgets.QLabel(self.layoutWidget_14)
        self.label142.setAlignment(QtCore.Qt.AlignCenter)
        self.label142.setObjectName("label142")
        self.verticalLayout_30.addWidget(self.label142)
        self.horizontalLayout_29.addLayout(self.verticalLayout_30)
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.textBrowser_14 = QtWidgets.QTextBrowser(self.layoutWidget_14)
        self.textBrowser_14.setMaximumSize(QtCore.QSize(174, 70))
        self.textBrowser_14.setObjectName("textBrowser_14")
        self.verticalLayout_31.addWidget(self.textBrowser_14)
        self.horizontalLayout_29.addLayout(self.verticalLayout_31)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.pushButton_19 = QtWidgets.QPushButton(self.layoutWidget_14)
        self.pushButton_19.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_30.addWidget(self.pushButton_19)
        self.horizontalLayout_29.addLayout(self.horizontalLayout_30)
        self.layoutWidget_15 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_15.setGeometry(QtCore.QRect(10, 1270, 301, 74))
        self.layoutWidget_15.setObjectName("layoutWidget_15")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.layoutWidget_15)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.label151 = QtWidgets.QLabel(self.layoutWidget_15)
        self.label151.setAlignment(QtCore.Qt.AlignCenter)
        self.label151.setObjectName("label151")
        self.verticalLayout_32.addWidget(self.label151)
        self.label152 = QtWidgets.QLabel(self.layoutWidget_15)
        self.label152.setAlignment(QtCore.Qt.AlignCenter)
        self.label152.setObjectName("label152")
        self.verticalLayout_32.addWidget(self.label152)
        self.horizontalLayout_31.addLayout(self.verticalLayout_32)
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.textBrowser_15 = QtWidgets.QTextBrowser(self.layoutWidget_15)
        self.textBrowser_15.setMaximumSize(QtCore.QSize(174, 70))
        self.textBrowser_15.setObjectName("textBrowser_15")
        self.verticalLayout_33.addWidget(self.textBrowser_15)
        self.horizontalLayout_31.addLayout(self.verticalLayout_33)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.pushButton_20 = QtWidgets.QPushButton(self.layoutWidget_15)
        self.pushButton_20.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_32.addWidget(self.pushButton_20)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_32)
        self.layoutWidget_16 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_16.setGeometry(QtCore.QRect(10, 1360, 301, 74))
        self.layoutWidget_16.setObjectName("layoutWidget_16")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.layoutWidget_16)
        self.horizontalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.label161 = QtWidgets.QLabel(self.layoutWidget_16)
        self.label161.setAlignment(QtCore.Qt.AlignCenter)
        self.label161.setObjectName("label161")
        self.verticalLayout_34.addWidget(self.label161)
        self.label162 = QtWidgets.QLabel(self.layoutWidget_16)
        self.label162.setAlignment(QtCore.Qt.AlignCenter)
        self.label162.setObjectName("label162")
        self.verticalLayout_34.addWidget(self.label162)
        self.horizontalLayout_33.addLayout(self.verticalLayout_34)
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.textBrowser_16 = QtWidgets.QTextBrowser(self.layoutWidget_16)
        self.textBrowser_16.setMaximumSize(QtCore.QSize(174, 70))
        self.textBrowser_16.setObjectName("textBrowser_16")
        self.verticalLayout_35.addWidget(self.textBrowser_16)
        self.horizontalLayout_33.addLayout(self.verticalLayout_35)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.pushButton_21 = QtWidgets.QPushButton(self.layoutWidget_16)
        self.pushButton_21.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_34.addWidget(self.pushButton_21)
        self.horizontalLayout_33.addLayout(self.horizontalLayout_34)
        self.layoutWidget_17 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_17.setGeometry(QtCore.QRect(10, 1450, 301, 74))
        self.layoutWidget_17.setObjectName("layoutWidget_17")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.layoutWidget_17)
        self.horizontalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.label171 = QtWidgets.QLabel(self.layoutWidget_17)
        self.label171.setAlignment(QtCore.Qt.AlignCenter)
        self.label171.setObjectName("label171")
        self.verticalLayout_36.addWidget(self.label171)
        self.label172 = QtWidgets.QLabel(self.layoutWidget_17)
        self.label172.setAlignment(QtCore.Qt.AlignCenter)
        self.label172.setObjectName("label172")
        self.verticalLayout_36.addWidget(self.label172)
        self.horizontalLayout_35.addLayout(self.verticalLayout_36)
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.textBrowser_17 = QtWidgets.QTextBrowser(self.layoutWidget_17)
        self.textBrowser_17.setMaximumSize(QtCore.QSize(174, 70))
        self.textBrowser_17.setObjectName("textBrowser_17")
        self.verticalLayout_37.addWidget(self.textBrowser_17)
        self.horizontalLayout_35.addLayout(self.verticalLayout_37)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.pushButton_22 = QtWidgets.QPushButton(self.layoutWidget_17)
        self.pushButton_22.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_36.addWidget(self.pushButton_22)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_36)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.rescrap_button = QtWidgets.QPushButton(self.layoutWidget)
        self.rescrap_button.setObjectName("rescrap_button")
        self.verticalLayout.addWidget(self.rescrap_button)
        self.broadcast_label = QtWidgets.QLabel(self.layoutWidget)
        self.broadcast_label.setAlignment(QtCore.Qt.AlignCenter)
        self.broadcast_label.setObjectName("broadcast_label")
        self.verticalLayout.addWidget(self.broadcast_label)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        DayTable.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DayTable)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 362, 28))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        DayTable.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DayTable)
        self.statusbar.setObjectName("statusbar")
        DayTable.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(DayTable)
        QtCore.QMetaObject.connectSlotsByName(DayTable)

    def retranslateUi(self, DayTable):
        _translate = QtCore.QCoreApplication.translate
        DayTable.setWindowTitle(_translate("DayTable", "MainWindow"))
        self.pushButton.setText(_translate("DayTable", "PushButton"))
        self.pushButton_2.setText(_translate("DayTable", "PushButton"))
        self.pushButton_3.setText(_translate("DayTable", "PushButton"))
        self.pushButton_4.setText(_translate("DayTable", "PushButton"))
        self.pushButton_5.setText(_translate("DayTable", "PushButton"))
        self.switch_button.setText(_translate("DayTable", "跳转至"))
        self.date_choose_button.setText(_translate("DayTable", "选择日期"))
        self.label11.setText(_translate("DayTable", "TextLabel"))
        self.label12.setText(_translate("DayTable", "TextLabel"))
        self.pushButton_6.setText(_translate("DayTable", "..."))
        self.label21.setText(_translate("DayTable", "TextLabel"))
        self.label22.setText(_translate("DayTable", "TextLabel"))
        self.pushButton_7.setText(_translate("DayTable", "..."))
        self.label31.setText(_translate("DayTable", "TextLabel"))
        self.label32.setText(_translate("DayTable", "TextLabel"))
        self.pushButton_8.setText(_translate("DayTable", "..."))
        self.label41.setText(_translate("DayTable", "TextLabel"))
        self.label42.setText(_translate("DayTable", "TextLabel"))
        self.pushButton_9.setText(_translate("DayTable", "..."))
        self.label51.setText(_translate("DayTable", "TextLabel"))
        self.label52.setText(_translate("DayTable", "TextLabel"))
        self.pushButton_10.setText(_translate("DayTable", "..."))
        self.label61.setText(_translate("DayTable", "TextLabel"))
        self.label62.setText(_translate("DayTable", "TextLabel"))
        self.pushButton_11.setText(_translate("DayTable", "..."))
        self.label71.setText(_translate("DayTable", "TextLabel"))
        self.label72.setText(_translate("DayTable", "TextLabel"))
        self.pushButton_12.setText(_translate("DayTable", "..."))
        self.label81.setText(_translate("DayTable", "TextLabel"))
        self.label82.setText(_translate("DayTable", "TextLabel"))
        self.pushButton_13.setText(_translate("DayTable", "..."))
        self.label91.setText(_translate("DayTable", "TextLabel"))
        self.label92.setText(_translate("DayTable", "TextLabel"))
        self.pushButton_14.setText(_translate("DayTable", "..."))
        self.label101.setText(_translate("DayTable", "TextLabel"))
        self.label102.setText(_translate("DayTable", "TextLabel"))
        self.pushButton_15.setText(_translate("DayTable", "..."))
        self.label111.setText(_translate("DayTable", "TextLabel"))
        self.label112.setText(_translate("DayTable", "TextLabel"))
        self.pushButton_16.setText(_translate("DayTable", "..."))
        self.label121.setText(_translate("DayTable", "TextLabel"))
        self.label122.setText(_translate("DayTable", "TextLabel"))
        self.pushButton_17.setText(_translate("DayTable", "..."))
        self.add_button.setText(_translate("DayTable", "add"))
        self.label131.setText(_translate("DayTable", "TextLabel"))
        self.label132.setText(_translate("DayTable", "TextLabel"))
        self.pushButton_18.setText(_translate("DayTable", "..."))
        self.label141.setText(_translate("DayTable", "TextLabel"))
        self.label142.setText(_translate("DayTable", "TextLabel"))
        self.pushButton_19.setText(_translate("DayTable", "..."))
        self.label151.setText(_translate("DayTable", "TextLabel"))
        self.label152.setText(_translate("DayTable", "TextLabel"))
        self.pushButton_20.setText(_translate("DayTable", "..."))
        self.label161.setText(_translate("DayTable", "TextLabel"))
        self.label162.setText(_translate("DayTable", "TextLabel"))
        self.pushButton_21.setText(_translate("DayTable", "..."))
        self.label171.setText(_translate("DayTable", "TextLabel"))
        self.label172.setText(_translate("DayTable", "TextLabel"))
        self.pushButton_22.setText(_translate("DayTable", "..."))
        self.rescrap_button.setText(_translate("DayTable", "课表有误？点击以重新爬取"))
        self.broadcast_label.setText(_translate("DayTable", "TextLabel"))
        self.menu.setTitle(_translate("DayTable", "文件"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DayTable = QtWidgets.QMainWindow()
    ui = Ui_DayTable()
    ui.setupUi(DayTable)
    DayTable.show()
    sys.exit(app.exec_())

