# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/shacoli/open-project/desktop-uestc/gui/WeekTable.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WeekTable(object):
    def setupUi(self, WeekTable):
        WeekTable.setObjectName("WeekTable")
        WeekTable.resize(324, 911)
        self.centralwidget = QtWidgets.QWidget(WeekTable)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 301, 851))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.switch_button = QtWidgets.QPushButton(self.widget)
        self.switch_button.setObjectName("switch_button")
        self.horizontalLayout.addWidget(self.switch_button)
        self.dateEdit = QtWidgets.QDateEdit(self.widget)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout.addWidget(self.dateEdit)
        self.date_choose_button = QtWidgets.QPushButton(self.widget)
        self.date_choose_button.setObjectName("date_choose_button")
        self.horizontalLayout.addWidget(self.date_choose_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setMinimumSize(QtCore.QSize(196, 600))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 281, 1600))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 1600))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.rescrap_button = QtWidgets.QPushButton(self.widget)
        self.rescrap_button.setObjectName("rescrap_button")
        self.verticalLayout.addWidget(self.rescrap_button)
        self.broadcast_label = QtWidgets.QLabel(self.widget)
        self.broadcast_label.setAlignment(QtCore.Qt.AlignCenter)
        self.broadcast_label.setObjectName("broadcast_label")
        self.verticalLayout.addWidget(self.broadcast_label)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        WeekTable.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WeekTable)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 324, 28))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        WeekTable.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WeekTable)
        self.statusbar.setObjectName("statusbar")
        WeekTable.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(WeekTable)
        QtCore.QMetaObject.connectSlotsByName(WeekTable)

    def retranslateUi(self, WeekTable):
        _translate = QtCore.QCoreApplication.translate
        WeekTable.setWindowTitle(_translate("WeekTable", "MainWindow"))
        self.pushButton.setText(_translate("WeekTable", "PushButton"))
        self.pushButton_2.setText(_translate("WeekTable", "PushButton"))
        self.pushButton_3.setText(_translate("WeekTable", "PushButton"))
        self.pushButton_4.setText(_translate("WeekTable", "PushButton"))
        self.pushButton_5.setText(_translate("WeekTable", "PushButton"))
        self.switch_button.setText(_translate("WeekTable", "跳转至"))
        self.date_choose_button.setText(_translate("WeekTable", "选择日期"))
        self.rescrap_button.setText(_translate("WeekTable", "课表有误？点击以重新爬取"))
        self.broadcast_label.setText(_translate("WeekTable", "TextLabel"))
        self.menu.setTitle(_translate("WeekTable", "文件"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WeekTable = QtWidgets.QMainWindow()
    ui = Ui_WeekTable()
    ui.setupUi(WeekTable)
    WeekTable.show()
    sys.exit(app.exec_())

