# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/shacoli/open-project/desktop-uestc/gui/WeekTable.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WeekTable(object):
    def setupUi(self, WeekTable):
        WeekTable.setObjectName("WeekTable")
        WeekTable.resize(319, 911)
        self.centralwidget = QtWidgets.QWidget(WeekTable)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(40, 50, 271, 731))
        self.scrollArea.setMinimumSize(QtCore.QSize(200, 600))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 255, 1200))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 1200))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.pushButton_14 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_14.setGeometry(QtCore.QRect(210, 1200, 31, 31))
        self.pushButton_14.setObjectName("pushButton_14")
        self.textBrowser_1 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser_1.setGeometry(QtCore.QRect(80, 10, 131, 81))
        self.textBrowser_1.setObjectName("textBrowser_1")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setGeometry(QtCore.QRect(220, 30, 31, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 120, 31, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser_2.setGeometry(QtCore.QRect(80, 100, 131, 81))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.layoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 120, 69, 42))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label21 = QtWidgets.QLabel(self.layoutWidget)
        self.label21.setObjectName("label21")
        self.verticalLayout_2.addWidget(self.label21)
        self.label22 = QtWidgets.QLabel(self.layoutWidget)
        self.label22.setObjectName("label22")
        self.verticalLayout_2.addWidget(self.label22)
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_3.setGeometry(QtCore.QRect(220, 210, 31, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser_3.setGeometry(QtCore.QRect(80, 190, 131, 81))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.layoutWidget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 210, 69, 42))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label31 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label31.setObjectName("label31")
        self.verticalLayout_3.addWidget(self.label31)
        self.label32 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label32.setObjectName("label32")
        self.verticalLayout_3.addWidget(self.label32)
        self.pushButton_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_4.setGeometry(QtCore.QRect(220, 300, 31, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser_4.setGeometry(QtCore.QRect(80, 280, 131, 81))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.layoutWidget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 300, 69, 42))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label41 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label41.setObjectName("label41")
        self.verticalLayout_4.addWidget(self.label41)
        self.label42 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label42.setObjectName("label42")
        self.verticalLayout_4.addWidget(self.label42)
        self.pushButton_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_5.setGeometry(QtCore.QRect(220, 390, 31, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser_5.setGeometry(QtCore.QRect(80, 370, 131, 81))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.layoutWidget_4 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_4.setGeometry(QtCore.QRect(0, 390, 69, 42))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label51 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label51.setObjectName("label51")
        self.verticalLayout_5.addWidget(self.label51)
        self.label52 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label52.setObjectName("label52")
        self.verticalLayout_5.addWidget(self.label52)
        self.pushButton_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_6.setGeometry(QtCore.QRect(220, 480, 31, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser_6.setGeometry(QtCore.QRect(80, 460, 131, 81))
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.layoutWidget_5 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_5.setGeometry(QtCore.QRect(0, 480, 69, 42))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label61 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label61.setObjectName("label61")
        self.verticalLayout_6.addWidget(self.label61)
        self.label62 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label62.setObjectName("label62")
        self.verticalLayout_6.addWidget(self.label62)
        self.pushButton_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_7.setGeometry(QtCore.QRect(220, 570, 31, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser_7.setGeometry(QtCore.QRect(80, 550, 131, 81))
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.layoutWidget_6 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_6.setGeometry(QtCore.QRect(0, 570, 69, 42))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label71 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label71.setObjectName("label71")
        self.verticalLayout_7.addWidget(self.label71)
        self.label72 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label72.setObjectName("label72")
        self.verticalLayout_7.addWidget(self.label72)
        self.pushButton_8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_8.setGeometry(QtCore.QRect(220, 660, 31, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser_8.setGeometry(QtCore.QRect(80, 640, 131, 81))
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.layoutWidget_7 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_7.setGeometry(QtCore.QRect(0, 660, 69, 42))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label81 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label81.setObjectName("label81")
        self.verticalLayout_8.addWidget(self.label81)
        self.label82 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label82.setObjectName("label82")
        self.verticalLayout_8.addWidget(self.label82)
        self.pushButton_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_9.setGeometry(QtCore.QRect(220, 750, 31, 31))
        self.pushButton_9.setObjectName("pushButton_9")
        self.textBrowser_9 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser_9.setGeometry(QtCore.QRect(80, 730, 131, 81))
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.layoutWidget_8 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_8.setGeometry(QtCore.QRect(0, 750, 69, 42))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label91 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label91.setObjectName("label91")
        self.verticalLayout_9.addWidget(self.label91)
        self.label92 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label92.setObjectName("label92")
        self.verticalLayout_9.addWidget(self.label92)
        self.pushButton_10 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_10.setGeometry(QtCore.QRect(220, 840, 31, 31))
        self.pushButton_10.setObjectName("pushButton_10")
        self.textBrowser_10 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser_10.setGeometry(QtCore.QRect(80, 820, 131, 81))
        self.textBrowser_10.setObjectName("textBrowser_10")
        self.layoutWidget_9 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_9.setGeometry(QtCore.QRect(0, 840, 69, 42))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget_9)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label101 = QtWidgets.QLabel(self.layoutWidget_9)
        self.label101.setObjectName("label101")
        self.verticalLayout_10.addWidget(self.label101)
        self.label102 = QtWidgets.QLabel(self.layoutWidget_9)
        self.label102.setObjectName("label102")
        self.verticalLayout_10.addWidget(self.label102)
        self.pushButton_11 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_11.setGeometry(QtCore.QRect(220, 930, 31, 31))
        self.pushButton_11.setObjectName("pushButton_11")
        self.textBrowser_11 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser_11.setGeometry(QtCore.QRect(80, 910, 131, 81))
        self.textBrowser_11.setObjectName("textBrowser_11")
        self.layoutWidget_10 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_10.setGeometry(QtCore.QRect(0, 930, 69, 42))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget_10)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label111 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label111.setObjectName("label111")
        self.verticalLayout_11.addWidget(self.label111)
        self.label112 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label112.setObjectName("label112")
        self.verticalLayout_11.addWidget(self.label112)
        self.pushButton_12 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_12.setGeometry(QtCore.QRect(220, 1020, 31, 31))
        self.pushButton_12.setObjectName("pushButton_12")
        self.textBrowser_12 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser_12.setGeometry(QtCore.QRect(80, 1000, 131, 81))
        self.textBrowser_12.setObjectName("textBrowser_12")
        self.layoutWidget_11 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_11.setGeometry(QtCore.QRect(0, 1020, 69, 42))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget_11)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label121 = QtWidgets.QLabel(self.layoutWidget_11)
        self.label121.setObjectName("label121")
        self.verticalLayout_12.addWidget(self.label121)
        self.label122 = QtWidgets.QLabel(self.layoutWidget_11)
        self.label122.setObjectName("label122")
        self.verticalLayout_12.addWidget(self.label122)
        self.pushButton_13 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_13.setGeometry(QtCore.QRect(220, 1110, 31, 31))
        self.pushButton_13.setObjectName("pushButton_13")
        self.textBrowser_13 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser_13.setGeometry(QtCore.QRect(80, 1090, 131, 81))
        self.textBrowser_13.setObjectName("textBrowser_13")
        self.layoutWidget_12 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_12.setGeometry(QtCore.QRect(0, 1110, 69, 42))
        self.layoutWidget_12.setObjectName("layoutWidget_12")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.layoutWidget_12)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label131 = QtWidgets.QLabel(self.layoutWidget_12)
        self.label131.setObjectName("label131")
        self.verticalLayout_13.addWidget(self.label131)
        self.label132 = QtWidgets.QLabel(self.layoutWidget_12)
        self.label132.setObjectName("label132")
        self.verticalLayout_13.addWidget(self.label132)
        self.layoutWidget1 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 30, 69, 42))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label11 = QtWidgets.QLabel(self.layoutWidget1)
        self.label11.setObjectName("label11")
        self.verticalLayout.addWidget(self.label11)
        self.label12 = QtWidgets.QLabel(self.layoutWidget1)
        self.label12.setObjectName("label12")
        self.verticalLayout.addWidget(self.label12)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.rescrap_button = QtWidgets.QPushButton(self.centralwidget)
        self.rescrap_button.setGeometry(QtCore.QRect(40, 780, 271, 25))
        self.rescrap_button.setObjectName("rescrap_button")
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(40, 20, 199, 33))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.switch_button = QtWidgets.QPushButton(self.layoutWidget2)
        self.switch_button.setObjectName("switch_button")
        self.horizontalLayout.addWidget(self.switch_button)
        self.dateEdit = QtWidgets.QDateEdit(self.layoutWidget2)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout.addWidget(self.dateEdit)
        self.broadcast_label = QtWidgets.QLabel(self.centralwidget)
        self.broadcast_label.setGeometry(QtCore.QRect(40, 810, 271, 17))
        self.broadcast_label.setAlignment(QtCore.Qt.AlignCenter)
        self.broadcast_label.setObjectName("broadcast_label")
        WeekTable.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WeekTable)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 319, 28))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        WeekTable.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WeekTable)
        self.statusbar.setObjectName("statusbar")
        WeekTable.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(WeekTable)
        QtCore.QMetaObject.connectSlotsByName(WeekTable)

    def retranslateUi(self, WeekTable):
        _translate = QtCore.QCoreApplication.translate
        WeekTable.setWindowTitle(_translate("WeekTable", "MainWindow"))
        self.pushButton_14.setText(_translate("WeekTable", "+"))
        self.pushButton.setText(_translate("WeekTable", "+"))
        self.pushButton_2.setText(_translate("WeekTable", "+"))
        self.label21.setText(_translate("WeekTable", "TextLabel"))
        self.label22.setText(_translate("WeekTable", "TextLabel"))
        self.pushButton_3.setText(_translate("WeekTable", "+"))
        self.label31.setText(_translate("WeekTable", "TextLabel"))
        self.label32.setText(_translate("WeekTable", "TextLabel"))
        self.pushButton_4.setText(_translate("WeekTable", "+"))
        self.label41.setText(_translate("WeekTable", "TextLabel"))
        self.label42.setText(_translate("WeekTable", "TextLabel"))
        self.pushButton_5.setText(_translate("WeekTable", "+"))
        self.label51.setText(_translate("WeekTable", "TextLabel"))
        self.label52.setText(_translate("WeekTable", "TextLabel"))
        self.pushButton_6.setText(_translate("WeekTable", "+"))
        self.label61.setText(_translate("WeekTable", "TextLabel"))
        self.label62.setText(_translate("WeekTable", "TextLabel"))
        self.pushButton_7.setText(_translate("WeekTable", "+"))
        self.label71.setText(_translate("WeekTable", "TextLabel"))
        self.label72.setText(_translate("WeekTable", "TextLabel"))
        self.pushButton_8.setText(_translate("WeekTable", "+"))
        self.label81.setText(_translate("WeekTable", "TextLabel"))
        self.label82.setText(_translate("WeekTable", "TextLabel"))
        self.pushButton_9.setText(_translate("WeekTable", "+"))
        self.label91.setText(_translate("WeekTable", "TextLabel"))
        self.label92.setText(_translate("WeekTable", "TextLabel"))
        self.pushButton_10.setText(_translate("WeekTable", "+"))
        self.label101.setText(_translate("WeekTable", "TextLabel"))
        self.label102.setText(_translate("WeekTable", "TextLabel"))
        self.pushButton_11.setText(_translate("WeekTable", "+"))
        self.label111.setText(_translate("WeekTable", "TextLabel"))
        self.label112.setText(_translate("WeekTable", "TextLabel"))
        self.pushButton_12.setText(_translate("WeekTable", "+"))
        self.label121.setText(_translate("WeekTable", "TextLabel"))
        self.label122.setText(_translate("WeekTable", "TextLabel"))
        self.pushButton_13.setText(_translate("WeekTable", "+"))
        self.label131.setText(_translate("WeekTable", "TextLabel"))
        self.label132.setText(_translate("WeekTable", "TextLabel"))
        self.label11.setText(_translate("WeekTable", "TextLabel"))
        self.label12.setText(_translate("WeekTable", "TextLabel"))
        self.rescrap_button.setText(_translate("WeekTable", "课标有误？点击以重新爬取"))
        self.switch_button.setText(_translate("WeekTable", "跳转至"))
        self.broadcast_label.setText(_translate("WeekTable", "TextLabel"))
        self.menu.setTitle(_translate("WeekTable", "文件"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WeekTable = QtWidgets.QMainWindow()
    ui = Ui_WeekTable()
    ui.setupUi(WeekTable)
    WeekTable.show()
    sys.exit(app.exec_())

